build:
  version: "1.0"

loans:
  message: "Welcome to NavyT accounts related local APIs "
  contactDetails:
    name: "TRAN Y VAN - developer"
    email: "van@trany.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345