build:
  version: "1.3"

loans:
  message: "Welcome to NavyT accounts related local APIs "
  contactDetails:
    name: "LY THANH TU - qa"
    email: "tu.lythanh@trany.com"
  onCallSupport:
    - (555) 101-1011
    - (555) 102-2349