build:
  version: "1.0"

accounts:
  message: "Welcome to NavyT accounts related local APIs "
  contactDetails:
    name: "Tran Y Van - Developer"
    email: "van@trany.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345