server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///home//vantycs//Documents//java-workspace//config"
        git:
          uri: "https://github.com/TranYVan/learn-microservice-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "99hQw0rA8tSPCHFrkzSLKIhGYLgGI7oP"