services:
  accounts:
    image: "yfangvjoker/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - yfangvjoker
  loans:
    image: "yfangvjoker/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - yfangvjoker
  cards:
    image: "yfangvjoker/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - yfangvjoker
networks:
  yfangvjoker:
      driver: "bridge"
